In [1]:
import numpy as np
import pandas as pd
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [2]:
np.mean([1, 2, 3, 4, 5])

3.0

In [3]:
np.dtype(float).itemsize # in bytes

8

In [4]:
np.ones(10, dtype='int') # generates 10 integer ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.random.random(10) # uniform on [0,1]

array([0.79757659, 0.24446364, 0.56075618, 0.41702033, 0.79043096,
       0.02559355, 0.9259923 , 0.42286881, 0.05129696, 0.22378188])

In [7]:
normal_array = np.random.randn(1000)
print("The sample mean and standard devation are %f and %f, respectively." %(np.mean(normal_array), np.std(normal_array)))

The sample mean and standard devation are -0.045077 and 1.038805, respectively.


In [8]:
first = np.ones(5)
second = np.ones(5)
first + second

array([2., 2., 2., 2., 2.])

In [9]:
first_list = [1., 1., 1., 1., 1.]
second_list = [1., 1., 1., 1., 1.]
first_list + second_list #not what u want

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [10]:
my_identity = np.eye(3)
print(my_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
twod = np.random.random(size=(5,2))
twod

array([[0.74519039, 0.6155131 ],
       [0.29576823, 0.43503516],
       [0.29406556, 0.12456026],
       [0.35504495, 0.30595664],
       [0.56524225, 0.59047005]])