In [1]:
import numpy as np
import pandas as pd
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [3]:
ages = np.array([13,25,19])
series1 = pd.Series(ages,index=['Emma', 'Swetha', 'Serajh'])
print(series1)

Emma      13
Swetha    25
Serajh    19
dtype: int64


In [7]:
np.mean([1, 2, 3, 4, 5])

3.0

In [9]:
np.dtype(float).itemsize # in bytes

8

In [10]:
np.ones(10, dtype='int') # generates 10 integer ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.random.random(10) # uniform on [0,1]

array([0.6951188 , 0.74426135, 0.87473665, 0.32884494, 0.18513938,
       0.42344512, 0.28980093, 0.13278814, 0.3625539 , 0.21976239])

In [13]:
normal_array = np.random.randn(1000)
print("The sample mean and standard devation are %f and %f, respectively." %(np.mean(normal_array), np.std(normal_array)))

The sample mean and standard devation are -0.024870 and 1.004363, respectively.


In [14]:
my_identity = np.eye(3)
print(my_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# create a dataframe
dframe = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['India', 'USA', 'China', 'Russia'])
#compute a formatted string from each floating point value in frame
changefn = lambda x: '%.2f' % x
# Make changes element-wise
dframe['d'].map(changefn)

India      1.82
USA        0.20
China     -0.36
Russia    -0.33
Name: d, dtype: object

In [22]:
# Create a sample dataframe
school = pd.DataFrame({'A': ['Jay', 'Usher', 'Nicky', 'Romero', 'Will'], 
      'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'], 
      'C': [26, 22, 20, 23, 24]})
# Lets create a pivot table to segregate students based on age and course
table = pd.pivot_table(school, values ='A', index =['B', 'C'], 
                         columns =['B'], aggfunc = np.sum, fill_value="Not Available") 
  
table

B                 Graduate        Masters
B        C                               
Graduate 20          Nicky  Not Available
         22          Usher  Not Available
         24           Will  Not Available
Masters  23  Not Available         Romero
         26  Not Available            Jay